version: '3.9'

services:
  create_certs:
    container_name: create_certs
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    command: >
      bash -c '
        if [[ ! -f ./config/certificates/elastic-certificates.p12 ]]; then
          bin/elasticsearch-certutil cert -out config/certificates/elastic-certificates.p12 -pass ""
        fi;
        chown -R 1000:0 /usr/share/elasticsearch/config/certificates
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['es-certs-volume:/usr/share/elasticsearch/config/certificates']


  elasticsearch:
    container_name: elas-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    restart: always
    networks:
      - backend
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      # - xpack.security.enabled=true
      # - xpack.security.authc.api_key.enabled=true
      # - ELASTIC_USERNAME=elastic
      # - ELASTIC_PASSWORD=es-magic
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode=certificate 
      # - xpack.security.transport.ssl.client_authentication=required
      # - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12
      # - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12
    volumes:
      - elastic-search-volume:/usr/share/elasticsearch/data
      - es-certs-volume:/usr/share/elasticsearch/config/certificates
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 1G

  
  kibana:
    container_name: kb-node
    image: docker.elastic.co/kibana/kibana:7.16.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elas-node:9200
      # - ELASTIC_USERNAME=elastic
      # - ELASTIC_PASSWORD=es-magic
    networks:
      - backend
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601


networks:
  backend:

volumes:
  elastic-search-volume:
  es-certs-volume:

